### ISSUE TITLE
Update database

### ISSUE THREAD

**Issue by gsurrel** [gsurrel/Terrovizm#31]
The database has been updated to include until 2018. It's already one year old. Maybe we can update the dataviz @m-doru?

I'm downloading the update and try to run your import scripts.

**Comment by gsurrel** [comment]
Database downloaded, processed, and website updated!

**Comment by m-doru** [comment]
Nice one, G!! Is it worth it another post on r/dataisbeautiful? :D

**Comment by gsurrel** [comment]
Given the (absence of) success last time, I guess the button that opens the access is not discoverable enough. It would be good to fix that, I guess?

**Comment by m-doru** [comment]
A fair point, I'm also experiencing some issues with the map tiles. I'll try to make some time in the next week to look into these two things and revert here
